In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [21]:
arr = np.array ([ [1,2,3] , [4,5,6] ])
result= arr * 2
result

(2, 3)

In [9]:
arr1 = np.array ([ [-1,2,0,4] , [4,-0.5,6,0], [2.6,0,7,8] ,[3,-7,4,2.0] ])
arr2 =arr1[:2 ,::2]
print ("the first 2 rows and alternate columns(0 and 2 ):\n" , arr2)

the first 2 rows and alternate columns(0 and 2 ):
 [[-1.  0.]
 [ 4.  6.]]


In [10]:
arr3 = arr1[[1,1,0,3] , [3,2,1,0]]
print ("\n Elements at indices (1,3) , (1,2) , (0,1) ,(3,0) : \n" , arr3)


 Elements at indices (1,3) , (1,2) , (0,1) ,(3,0) : 
 [0. 6. 2. 3.]


In [17]:
a= np.array([[1,2] , [3,4]])
b= np.array([[1,2] , [3,4]])

print("Plus 1 to every mtx A element:" , a+1)
print("\nMinus 2 to every mtx B element:" , b-2)
print ("\nSum of all array elements:", a.sum())
print("\nArray sum:\n", a+b)

Plus 1 to every mtx A element: [[2 3]
 [4 5]]

Minus 2 to every mtx B element: [[-1  0]
 [ 1  2]]

Sum of all array elements: 10

Array sum:
 [[2 4]
 [6 8]]


In [22]:
# array dimension
arr = np.array ([ [1,2,3] , [4,5,6] ])
arr.shape

(2, 3)

In [34]:
x= np.array([[-11,2] , [1,-4]])
y= np.array([[16,9] , [25,4]], dtype=np.float64)

print ("data type of x :" , x.dtype)
print ("data type of y :" , y.dtype)

data type of x : int64
data type of y : float64


In [35]:
sum = np.add(x,y)
sum

array([[ 5., 11.],
       [26.,  0.]])

In [36]:
sum1 = np.sum(x)
sum1

np.int64(-12)

In [37]:
SqrtOfy = np.sqrt(y)
SqrtOfy

array([[4., 3.],
       [5., 2.]])

In [48]:
transpose_x = x.T
transpose_y = y.T
print ("transpose of x :\n", transpose_x)
print ("\ntranspose of y :\n", transpose_y)

transpose of x :
 [[-11   1]
 [  2  -4]]

transpose of y :
 [[16. 25.]
 [ 9.  4.]]


In [50]:
mtx = np.array ([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
    [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
    [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
    [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
])

myArr=mtx[1:8,::3]
myArr

array([[11, 14, 17, 20],
       [21, 24, 27, 30],
       [31, 34, 37, 40],
       [41, 44, 47, 50],
       [51, 54, 57, 60],
       [61, 64, 67, 70],
       [71, 74, 77, 80]])

In [53]:
transposeofMtx = mtx.T
transposeofMtx

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [64]:
reshaped = np.reshape(mtx, (10,10))  
reshaped

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [68]:
vector = np.array([1, 2, 3, 4])
column_vector = vector.reshape(4, 1)
column_vector

   

array([[1],
       [2],
       [3],
       [4]])